#pragma config(Sensor, dgtl1,  EncoderToUse,   sensorRotation)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Cat1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Cat2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Cat3Conveyer,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ClimbingMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static void LongBack()
{
	int ConditionToIt = 0;
	SensorValue[EncoderToUse] = 0;
	while(true)
	{

		while(SensorValue[EncoderToUse] <= 500 && ConditionToIt == 0)
		{
			motor[Cat1] = 0;
			motor[Cat2] = 0;
			motor[Cat3Conveyer] = 0;
			//forward again
			motor[frontRight] = 100;
			motor[frontLeft] = 0;
			motor[backRight] = -100;
			motor[backLeft] =  -100;
			ConditionToIt++;
		}
		if(SensorValue[EncoderToUse] >=500)
		{
			//SensorValue[EncoderToUse] = 0;
			//backwards
			motor[frontRight] = -100;
			motor[frontLeft] = -100;
			motor[backRight] = 100;
			motor[backLeft] = 100;
		}
		if(SensorValue[EncoderToUse] >=1000 && ConditionToIt == 0)
		{
			SensorValue[EncoderToUse] = 0;
		}
		if(SensorValue[EncoderToUse] <= 500 && ConditionToIt == 1)
		{
			//	SensorValue[EncoderToUse] = 0;
			motor[frontRight] = -100;
			motor[frontLeft] = 100;
			motor[backRight] = -100;
			motor[backLeft] = 100;
		}
		if(SensorValue[EncoderToUse] >=1000 && ConditionToIt == 1)
		{
			motor[frontRight] = 0;
			motor[frontLeft] = 0;
			motor[backRight] = 0;
			motor[backLeft] = 0;
			break;
		}
	}
}


task main()
{
	//motor[backLeft] =  -100;
	SensorValue[EncoderToUse] = 0;
	//if(vexRT[Btn8U] ==1)
	//{
		while(true)
		{


			//	if(vexRT[Btn5D] == 1)
			//{
			//SensorValue[EncoderToUse] = 0;
			if(SensorValue[EncoderToUse] <= 250)
			{

				//forward


				motor[frontRight] = 100;
				motor[frontLeft] = 100;
				motor[backRight] = -100;
				motor[backLeft] =  -100;



			}
			else //if(SensorValue[EncoderToUse] >=250)
			{
				//stop
				motor[frontRight] = 0;
				motor[frontLeft] = 0;
				motor[backRight] = 0;
				motor[backLeft] =  0;
				wait1Msec(2000);
				//shoot catapult
				motor[Cat1] = 100;
				motor[Cat2] = -100;
				motor[Cat3Conveyer] = 100;


				//	SensorValue[EncoderToUse] = 0;
				LongBack();
				break;
			}
		}
	}



//move towards the platform
//move left



/*	wait1Msec(100);
motor[frontRight] = 60;
motor[frontLeft] = -60;
motor[backRight] = 60;
motor[backLeft] = -60;
wait1Msec(100);
motor[frontRight] = 0;
motor[frontLeft] = 0;
motor[backRight] = 0;
motor[backLeft] = 0;*/


//	}
